# test_bbdd.py - Generated by CodiumAI

import pytest
import os
import sys
from unittest import TestCase

directori = os.path.dirname(os.path.dirname(__file__))
sys.path.append(os.path.join(directori, "src"))

from moduls.bbdd import Lectormateries, Lectorbbdd, Lectorsabers, Connectorbbdd


class TestLector(TestCase):
    """Comprova la classe Lector"""

    def test_mode_testing(self):
        """Comprova la ruta de l'arxiu de base de dades en el mode testeig"""
        lector = Lectorbbdd(0)
        self.assertEqual(lector.ruta_arxiu_bbdd, "/home/jordi/Documents/Projectes/Progpy/tests/test.db",
                         msg="La ruta de l'arxiu en mode testeig no es correcte")

    def test_mode_produccio(self):
        """Comprova la ruta de l'arxiu de base de dades en el mode de producció"""
        lector = Lectorbbdd(1)
        self.assertEqual(lector.ruta_arxiu_bbdd, "/home/jordi/Documents/Projectes/Progpy/src/dades/dades.db",
                         msg="La ruta de l'arxiu en mode producció no es correcte")

    def test_valors_invalids(self):
        """Comprova si la classe Lector accepta valors invàlids"""
        self.assertRaises(ValueError, Lectorbbdd, 2)


class TestConnector(TestCase):
    """Comprova la classe Connectorbbdd"""

    def test_mode_testing(self):
        """Comprova la connexió a la base de dades en el mode de test"""
        connector = Connectorbbdd(0)
        self.assertEqual(connector.ruta_arxiu_bbdd, "/home/jordi/Documents/Projectes/Progpy/tests/test.db",
                         msg="La ruta de l'arxiu en mode testeig no es correcte")

    def test_mode_produccio(self):
        """Comprova la connexió a la base de dades en el mode de producció"""
        connector = Connectorbbdd(1)
        self.assertEqual(connector.ruta_arxiu_bbdd, "/home/jordi/Documents/Projectes/Progpy/src/dades/dades.db",
                         msg="La ruta de l'arxiu en mode producció no es correcte")


class TestLlistadormateries(TestCase):
    """Comprova la classe Lectormateries"""

    def test_llistar_materies_error_taula(self):
        """Comprova que amb una taula errònia, genera un avís"""
        llistat = Lectormateries(0)
        llistat.taula = "materies"
        self.assertRaises(Warning, msg="La classe Llistador materies no provoca un warning quan la taula no és "
                                       "correcte")

    def test_llistar_materies(self):
        """Comprova que retorna una llista de totes les matèries de la base de dades"""
        llistat = Lectormateries(0)
        self.assertTrue(isinstance(llistat.llistar_materies(), list))

    def test_llistar_materies_completes(self):
        """Comprova que retorna una llista de totes les matèries de la base de dades"""
        llistat = Lectormateries(0)
        self.assertTrue(isinstance(llistat.llistar_materies_completes(), list))

    def test_llistar_materies_combinades(self):
        """Comprova que retorna una llista de totes les matèries de la base de dades"""
        llistat = Lectormateries(0)
        self.assertTrue(isinstance(llistat.combinar_info_materies(), list))

    def test_llistar_materies_completes_llargada(self):
        """Comprova que retorna una llista de totes les matèries de la base de dades"""
        llistat = Lectormateries(0)
        self.assertTrue(len(llistat.combinar_info_materies()) > 0)

    def test_llistar_materies_error_bbdd(self):
        """Comprova que amb una bbdd errònia, genera un avís"""
        llistat = Lectormateries(0)
        llistat.ruta_arxiu_bbdd = "/home/jordi/Documents/Projectes/Progpy/tests/dummy.db"
        self.assertRaises(ValueError, msg="La classe Llistador materies no provoca un warning quan la bbdd no és ")


class TestLlistadorSabers(TestCase):
    """Comprova la classe Lectorsabers"""

    def test_llistar_sabers_error_taula(self):
        """Comprova que amb una taula errònia, genera un avís"""
        llistat = Lectorsabers(0)
        llistat.taula = "saber"
        self.assertRaises(Warning, msg="La classe Llistador materies no provoca un warning quan la taula no és "
                                       "correcte")

    def test_llistar_sabers(self):
        """Comprova que amb una taula errònia, genera un avís"""
        llistat = Lectorsabers(0)
        retorn = llistat.consulta_no_filtrada()
        self.assertTrue(isinstance(retorn, list))

    def test_saber_id(self):
        """Comprova que s'obté una llista amb un saber especificant l'id"""
        llistat = Lectorsabers(0)
        retorn = llistat.consulta_id(1)
        self.assertTrue(retorn == [(1, 'Resolució de problemes i situacions de la vida quotidiana en els quals s’hagin'
                                       ' de fer recomptes sistemàtics, utilitzant diferents estratègies (diagrames '
                                       'd’arbre, tècniques de combinatòria, etc.)')])

    def test_saber_descripcio(self):
        """Comprova que s'obté una llista amb un saber especificant l'id"""
        llistat = Lectorsabers(0)
        retorn = llistat.consulta_descripcio('Resolució de problemes i situacions de la vida quotidiana en els quals '
                                             's’hagin de fer recomptes sistemàtics, utilitzant diferents estratègies '
                                             '(diagrames d’arbre, tècniques de combinatòria, etc.)')
        self.assertTrue(retorn == 1)

    def test_llistar_sabers_longitud_positiva(self):
        """Comprova que retorna una llista de totes les matèries de la base de dades"""
        llistat = Lectorsabers(0)
        self.assertTrue(len(llistat.consulta_no_filtrada()) > 0)

    def test_llistar_sabers_blocs(self):
        """Comprova que amb una taula errònia, genera un avís"""
        llistat = Lectorsabers(0)
        retorn = llistat.consulta_blocs()
        self.assertTrue(isinstance(retorn, list))

    def test_llistar_sabers_blocs_longitud_positiva(self):
        """Comprova que retorna una llista de totes les matèries de la base de dades"""
        llistat = Lectorsabers(0)
        self.assertTrue(len(llistat.consulta_blocs()) > 0)

    def test_llistar_sabers_blocs_id(self):
        """Comprova que es retorna una llista especificant l'id dels sabers"""
        llistat = Lectorsabers(0)
        retorn = llistat.consulta_bloc_id(1)
        self.assertTrue(retorn, [(1, 'Resolució de problemes i situacions de la vida quotidiana en els quals s’hagin de'
                                     ' fer recomptes sistemàtics, utilitzant diferents estratègies (diagrames d’arbre, '
                                     'tècniques de combinatòria, etc.)', 1, 'Sentit numèric')])




if __name__ == '__main__':
    pytest.main()
