
# Generated by CodiumAI
from bbdd.estudis import GeneradorArbreMateries


import pytest

class TestGeneradorArbreMateries:
    # Test that the object 'GeneradorArbreMateries' is initialized with the correct parameters
    def test_initialization_with_correct_parameters(self):
        generador_test = GeneradorArbreMateries(0)
        generador_produccio = GeneradorArbreMateries(1)
        assert generador_test.ruta_arxiu_bbdd == arrel_tests
        assert generador_produccio.ruta_arxiu_bbdd == arrel_produccio

